/* Generated By:JavaCC: Do not edit this line. dappConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface dappConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int NAME = 11;
  /** RegularExpression Id. */
  int NUMERIC_LITERAL = 12;
  /** RegularExpression Id. */
  int STRING_LITERAL = 13;
  /** RegularExpression Id. */
  int ARROW = 14;
  /** RegularExpression Id. */
  int LOGICAL_LITERAL = 15;
  /** RegularExpression Id. */
  int LESS = 16;
  /** RegularExpression Id. */
  int LESS_EQUAL = 17;
  /** RegularExpression Id. */
  int GREATER = 18;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 19;
  /** RegularExpression Id. */
  int EQUAL = 20;
  /** RegularExpression Id. */
  int NOT_EQUAL = 21;
  /** RegularExpression Id. */
  int PLUS = 22;
  /** RegularExpression Id. */
  int MINUS = 23;
  /** RegularExpression Id. */
  int MULT = 24;
  /** RegularExpression Id. */
  int DIV = 25;
  /** RegularExpression Id. */
  int POW = 26;
  /** RegularExpression Id. */
  int AND = 27;
  /** RegularExpression Id. */
  int OR = 28;
  /** RegularExpression Id. */
  int NOT = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;
  /** RegularExpression Id. */
  int COMMA = 31;
  /** RegularExpression Id. */
  int L_PAREN = 32;
  /** RegularExpression Id. */
  int R_PAREN = 33;
  /** RegularExpression Id. */
  int L_BRACKET = 34;
  /** RegularExpression Id. */
  int R_BRACKET = 35;
  /** RegularExpression Id. */
  int L_BRACE = 36;
  /** RegularExpression Id. */
  int R_BRACE = 37;
  /** RegularExpression Id. */
  int COLON = 38;
  /** RegularExpression Id. */
  int SEMI_COLON = 39;
  /** RegularExpression Id. */
  int QUESTION = 40;
  /** RegularExpression Id. */
  int DOT = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "\"\\uc2dc\\uc791\"",
    "\"\\uc744\"",
    "\"\\ub97c\"",
    "\"\\ud3ec\\ud568\"",
    "\"\\ub05d\"",
    "<NAME>",
    "<NUMERIC_LITERAL>",
    "<STRING_LITERAL>",
    "\"->\"",
    "<LOGICAL_LITERAL>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\"?\"",
    "\".\"",
    "<IDENTIFIER>",
    "\"\\\"\"",
  };

}
