/* Generated By:JavaCC: Do not edit this line. dappConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface dappConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int DOT = 30;
  /** RegularExpression Id. */
  int ENG_NAME = 31;
  /** RegularExpression Id. */
  int NAME = 32;
  /** RegularExpression Id. */
  int NUMERIC_LITERAL = 33;
  /** RegularExpression Id. */
  int STRING_LITERAL = 34;
  /** RegularExpression Id. */
  int ARROW = 35;
  /** RegularExpression Id. */
  int LOGICAL_LITERAL = 36;
  /** RegularExpression Id. */
  int LESS = 37;
  /** RegularExpression Id. */
  int LESS_EQUAL = 38;
  /** RegularExpression Id. */
  int GREATER = 39;
  /** RegularExpression Id. */
  int GREATER_EQUAL = 40;
  /** RegularExpression Id. */
  int EQUAL = 41;
  /** RegularExpression Id. */
  int NOT_EQUAL = 42;
  /** RegularExpression Id. */
  int PLUS = 43;
  /** RegularExpression Id. */
  int MINUS = 44;
  /** RegularExpression Id. */
  int MULT = 45;
  /** RegularExpression Id. */
  int DIV = 46;
  /** RegularExpression Id. */
  int POW = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int NOT = 50;
  /** RegularExpression Id. */
  int ASSIGN = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int L_PAREN = 53;
  /** RegularExpression Id. */
  int R_PAREN = 54;
  /** RegularExpression Id. */
  int L_BRACKET = 55;
  /** RegularExpression Id. */
  int R_BRACKET = 56;
  /** RegularExpression Id. */
  int L_BRACE = 57;
  /** RegularExpression Id. */
  int R_BRACE = 58;
  /** RegularExpression Id. */
  int COLON = 59;
  /** RegularExpression Id. */
  int SEMI_COLON = 60;
  /** RegularExpression Id. */
  int QUESTION = 61;
  /** RegularExpression Id. */
  int IDENTIFIER = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<LETTER>",
    "\"\\uc2dc\\uc791\"",
    "\"\\uc744\"",
    "\"\\ub97c\"",
    "\"\\ub85c\"",
    "\"\\uc73c\\ub85c\"",
    "\"\\ud3ec\\ud568\"",
    "\"\\ub05d\"",
    "\"\\uc815\\uc218\\ud615\"",
    "\"\\uc2e4\\uc218\\ud615\"",
    "\"\\ube48\\ud615\"",
    "\"\\ub9de\\ub2c8\\ud615\"",
    "\"\\uae00\\uc790\\ud615\"",
    "\"\\ubb38\\uc7a5\\ud615\"",
    "\"\\uc0dd\\uc131\"",
    "\"\\ub9cc\\uc57d\"",
    "\"\\ub77c\\uba74\"",
    "\"\\uc544\\ub2c8\\uace0\"",
    "\"\\uc544\\ub2c8\\uba74\"",
    "\"\\uadf8\\uce58\\ub9cc\"",
    "\"\\ud558\\uba74\"",
    "\"\\ud558\\ub294\\uac78\"",
    "\"\\uc77c \\ub54c\"",
    "\"\\uc5d0\"",
    "\"\\ub300\\uc785\"",
    "\".\"",
    "<ENG_NAME>",
    "<NAME>",
    "<NUMERIC_LITERAL>",
    "<STRING_LITERAL>",
    "\"->\"",
    "<LOGICAL_LITERAL>",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\";\"",
    "\"?\"",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"%\"",
  };

}
